---
# Install postgresql on DB server
- hosts: appdbs
  become: true

  tasks:

  - name: install postgres
    yum:
      name: postgresql-server
      state: latest

  - name: initilize postgres
    command: postgresql-setup initdb

  - name: start & enable postgres server
    service: 
      name: postgresql
      state: started
      enabled: yes