---
# Install HA Proxy on frontend server
- hosts: frontends
  become: true

  tasks:

#- name: install httpie
#  package:
#    name: httpie
#    state: latest

  - name: install haproxy
    yum:
      name: haproxy
      state: latest

  - name: start & enable haproxy
    service:
      name: haproxy
      state: started
      enabled: yes

  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:
  - name: restart haproxy
    service: 
      name: haproxy
      state: restarted
